#!/system/bin/sh
# Simple cached memory cleaner written by sakindia123
echo " ***** CyanogenMod 9 Turbo-Booster***** "
sync;
sleep 1
echo "3" > /proc/sys/vm/drop_caches;
echo "1" > /proc/sys/vm/drop_caches;
sleep 1
echo "** Your Phone has Been Turbo Boosted ** ";


